# Generated by Django 3.2.9 on 2022-05-26 15:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('primary_contact_name', models.CharField(default='Name', max_length=30)),
                ('primary_contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('secondary_contact_name', models.CharField(default='Name', max_length=30)),
                ('secondary_contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('hot_lunch', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
                ('transport_fee', models.IntegerField(default=3000)),
                ('current_grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_grade', to='grade.grade')),
                ('grade_admitted_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grade.grade')),
            ],
        ),
    ]
