# Generated by Django 3.2.9 on 2022-05-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='for_term',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='for_year',
            field=models.IntegerField(default=2022),
        ),
    ]
