# Generated by Django 3.2.9 on 2022-06-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0002_auto_20220529_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='description',
            field=models.CharField(default="term's fees", max_length=20),
        ),
    ]
