# Generated by Django 3.2.9 on 2022-06-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0003_financialaccount_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccount',
            name='description',
            field=models.CharField(default="term's fees ", max_length=20),
        ),
    ]
