# Generated by Django 3.2.9 on 2022-06-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='charge_admission_fee',
            field=models.BooleanField(),
        ),
    ]
